import "./scss/main.scss";
import Header from "./components/header";
import { montserrat } from "./components/font";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} main`}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
